// packages/demo-codemirror-6-webpack-react/src/App.js
import React from "react";

import { App as AppBase, Database } from "demo-base-react";
import CypherEditor from "react-codemirror-cypher";

const App = () => {
  return (
    <AppBase codemirrorVersion="6" framework="react" bundler="webpack">
      <Database CypherEditor={CypherEditor} />
    </AppBase>
  );
};

export default App;

// demos/demo-codemirror-6-webpack-svelte/src/App.svelte
<!--

-->
<script lang="ts">
  import { App, Database } from "demo-base-svelte";
  import { CypherEditor } from "@neo4j-cypher/svelte-codemirror";
</script>

<App>
  <Database
    slot="database"
    codemirrorVersion="6"
    framework="svelte"
    bundler="webpack"
    editor={CypherEditor}
  />
</App>
