// demos/demo-codemirror-6-vite-svelte/src/App.svelte
<!--
/*
 * Copyright (c) "Neo4j"
 * Neo4j Sweden AB [http://neo4j.com]
 *
 * This file is part of Neo4j.
 *
 * Neo4j is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
-->
<script lang="ts">
  import { App, Database } from "demo-base-svelte";
  import { CypherEditor } from "@neo4j-cypher/svelte-codemirror";
</script>

<App>
  <Database
    slot="database"
    codemirrorVersion="6"
    framework="svelte"
    bundler="vite"
    editor={CypherEditor}
  />
</App>

// demos/demo-codemirror-6-webpack-react/src/App.js
/*
 * Copyright (c) "Neo4j"
 * Neo4j Sweden AB [http://neo4j.com]
 *
 * This file is part of Neo4j.
 *
 * Neo4j is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

import React from "react";

import { App as AppBase, Database } from "demo-base-react";
import { CypherEditor } from "@neo4j-cypher/react-codemirror";

const App = () => {
  return (
    <AppBase>
      <Database
        codemirrorVersion="6"
        framework="react"
        bundler="webpack"
        CypherEditor={CypherEditor}
      />
    </AppBase>
  );
};

export default App;
