// packages/demo-base-svelte/src/Database.svelte
<script lang="ts">
  import neo4j from "neo4j-driver";
  import { neo4jSchema, simpleSchema, longQuery, simpleQuery, defaultOptions, initialPosition, host, user, pass } from "demo-base";

  export let codemirrorVersion = undefined;
  export let framework = undefined;
  export let bundler = undefined;
  export let editor = undefined;

  const initialSchema = simpleSchema;
  const title = `Cypher Codemirror ${codemirrorVersion} ${framework} ${bundler}`;

  const samplePlaceholder = "Sample Placeholder";

  const defaultLineNumberFormatter = undefined;
  const noneLineNumberFormatter = line => line;
  const customLineNumberFormatter = (line, lineCount) => {
    if (line === 1) {
      return "one";
    } else if (line === 2) {
      return "two";
    } else if (line === 3) {
      return "three";
    } else if (line > 3) {
      return line + ' / ' + lineCount + " prompt$";
    }
  };

  const initialValue = longQuery;
  const initialOptions = defaultOptions;
  let cypher = initialValue;

  const driver = neo4j.driver(
    host,
    neo4j.auth.basic(user, pass)
  );

  let theme = "light";
  let position = initialPosition || { line: 1, column: 0 };
  let focused = true;
  let lineNumbers = initialOptions.lineNumbers;
  let readOnly = initialOptions.readOnly;
  let autocomplete = initialOptions.autocomplete;
  let placeholder = initialOptions.placeholder;
  let autocompleteOpen = false;
  let lint = initialOptions.lint;
  let lineNumberFormatter = initialOptions.lineNumberFormatter;
  let schema = initialSchema;
  let cypherEditor;
  let autocompleteTriggerStrings = initialOptions.autocompleteTriggerStrings;
  let autocompleteSticky = initialOptions.autocompleteSticky;
  let positionPosition = "0";
  let positionLine = "1";
  let positionColumn = "0";
  let lineCount = 0;
  let logs = [];

  const commandLog = (command, argument) => {
    return {
      type: "command",
      label: command,
      command,
      argument
    };
  };

  const eventLog = (event, argument) => {
    return {
      type: "event",
      label: event,
      event,
      argument
    };
  };

  const lightTheme = () => {
    theme = "light";
    logs = logs.concat(commandLog("setTheme", theme));
  };

  const darkTheme = () => {
    theme = "dark";
    logs = logs.concat(commandLog("setTheme", theme));
  };

  let promisedResult;

  const send = () => {
    const session = driver.session();
    promisedResult = session.run(cypher);
  };

  let goPositionPositionEnabled;
  let goPositionLineColumnEnabled;

  const updateGoButtons = () => {
    goPositionPositionEnabled = isNumberString(positionPosition) && cypherEditor.getPositionForValue(+positionPosition) !== null;
    goPositionLineColumnEnabled = isNumberString(positionLine) && isNumberString(positionColumn) && cypherEditor.getPositionForValue({ line: +positionLine, column: +positionColumn }) !== null;
  };

  const updateValue = (value) => {
    cypher = value;
    updateGoButtons();
    if (cypherEditor) {
      lineCount = cypherEditor.getLineCount();
    }
  };

  const onValueChange = (value: string, change?: any) => {
    updateValue(value);
    logs = logs.concat(eventLog("onValueChange", value ? value.length : 0));
  };

  const onPositionChange = (positionObject) => {
    position = positionObject;
    logs = logs.concat(eventLog("onPositionChange", position));
  };

  const onAutocompleteOpenChange = (newAutocompleteOpen) => {
    autocompleteOpen = newAutocompleteOpen;
    logs = logs.concat(eventLog("onAutocompleteOpenChange", autocompleteOpen));
  };

  const onLineClick = (line, event) => {
    logs = logs.concat(eventLog("onLineClick", line));
  };

  const onEditorCreate = (editor) => {
    cypherEditor = editor;
    position = editor.getPosition();
    lineCount = cypherEditor.getLineCount();
    updateGoButtons();
    logs = logs.concat(eventLog("onEditorCreate", ""));
  };

  const onFocusChange = (newFocused) => {
    focused = newFocused;
    logs = logs.concat(eventLog("onFocusChange", focused));
  }

  const showLineNumbers = () => {
    lineNumbers = true;
    cypherEditor && cypherEditor.setLineNumbers(lineNumbers);
    logs = logs.concat(commandLog("setLineNumbers", lineNumbers));
  };

  const hideLineNumbers = () => {
    lineNumbers = false;
    cypherEditor && cypherEditor.setLineNumbers(lineNumbers);
    logs = logs.concat(commandLog("setLineNumbers", lineNumbers));
  };

  const printArgument = argument => {
    try {
      return JSON.stringify(argument);
    } catch (e) {
      return "error " + e.message + " " + argument;
    }
  };

  $: cypherLength = cypher ? cypher.length : 0;
  $: positionString = position ? JSON.stringify(position) : "";
  $: focusedString = focused + "";
  $: autocompleteString = autocompleteOpen + "";
  $: logText = logs.map(({ type, label, argument }) => type + " " + label + " " + printArgument(argument)).join("\n");

  const setNoPlaceholder = () => {
    placeholder = undefined;
    cypherEditor && cypherEditor.setPlaceholder(placeholder);
    logs = logs.concat(commandLog("setPlaceholder", placeholder));
  };

  const setSamplePlaceholder = () => {
    placeholder = samplePlaceholder;
    cypherEditor && cypherEditor.setPlaceholder(placeholder);
    logs = logs.concat(commandLog("setPlaceholder", placeholder));
  };

  const makeReadable = () => {
    readOnly = false;
    cypherEditor && cypherEditor.setReadOnly(readOnly);
    logs = logs.concat(commandLog("setReadOnly", readOnly));
  };

  const makeReadOnly = () => {
    readOnly = true;
    cypherEditor && cypherEditor.setReadOnly(readOnly);
    logs = logs.concat(commandLog("setReadOnly", readOnly));
  };

  const makeReadOnlyNoCursor = () => {
    readOnly = "nocursor";
    cypherEditor && cypherEditor.setReadOnly(readOnly);
    logs = logs.concat(commandLog("setReadOnly", readOnly));
  };

  const enableAutocomplete = () => {
    autocomplete = true;
    cypherEditor && cypherEditor.setAutocomplete(true);
    logs = logs.concat(commandLog("setAutocomplete", autocomplete));
  };

  const disableAutocomplete = () => {
    autocomplete = false;
    cypherEditor && cypherEditor.setAutocomplete(false);
    logs = logs.concat(commandLog("setAutocomplete", autocomplete));
  };

  const enableLint = () => {
    lint = true;
    cypherEditor && cypherEditor.setLint(lint);
    logs = logs.concat(commandLog("setLint", lint));
  };

  const disableLint = () => {
    lint = false;
    cypherEditor && cypherEditor.setLint(lint);
    logs = logs.concat(commandLog("setLint", lint));
  };

  const clearHistory = () => {
    cypherEditor && cypherEditor.clearHistory();
    logs = logs.concat(commandLog("clearHistory", ""));
  };

  const focusEditor = () => {
    cypherEditor && cypherEditor.focus();
    logs = logs.concat(commandLog("focus", ""));
  };

  const showDefaultLineNumberFormatter = () => {
    lineNumberFormatter = defaultLineNumberFormatter;
    cypherEditor && cypherEditor.setLineNumberFormatter(lineNumberFormatter);
    logs = logs.concat(commandLog("setLineNumberFormatter", "default " + typeof lineNumberFormatter));
  };

  const showNoneLineNumberFormatter = () => {
    lineNumberFormatter = noneLineNumberFormatter;
    cypherEditor && cypherEditor.setLineNumberFormatter(lineNumberFormatter);
    logs = logs.concat(commandLog("setLineNumberFormatter", "none " + typeof lineNumberFormatter));
  };

  const showCustomLineNumberFormatter = () => {
    lineNumberFormatter = customLineNumberFormatter;
    cypherEditor && cypherEditor.setLineNumberFormatter(lineNumberFormatter);
    logs = logs.concat(commandLog("setLineNumberFormatter", "custom " + typeof lineNumberFormatter));
  };

  const showSimpleSchema = () => {
    schema = simpleSchema;
    cypherEditor && cypherEditor.setSchema(schema);
    logs = logs.concat(commandLog("setSchema", "simple"));
  };

  const showLongSchema = () => {
    schema = neo4jSchema;
    cypherEditor && cypherEditor.setSchema(schema);
    logs = logs.concat(commandLog("setSchema", "long"));
  };

  const showDefaultAutocompleteTriggerStrings = () => {
    autocompleteTriggerStrings = initialOptions.autocompleteTriggerStrings;
    cypherEditor && cypherEditor.setAutocompleteTriggerStrings(initialOptions.autocompleteTriggerStrings);
    logs = logs.concat(commandLog("setAutocompleteTriggerStrings", autocompleteTriggerStrings));
  };

  const showNoAutocompleteTriggerStrings = () => {
    autocompleteTriggerStrings = false;
    cypherEditor && cypherEditor.setAutocompleteTriggerStrings(false);
    logs = logs.concat(commandLog("setAutocompleteTriggerStrings", autocompleteTriggerStrings));
  };

  const showStickyAutocomplete = () => {
    autocompleteSticky = true;
    cypherEditor && cypherEditor.setAutocompleteSticky(true);
    logs = logs.concat(commandLog("setAutocompleteSticky", autocompleteSticky));
  };

  const showUnstickyAutocomplete = () => {
    autocompleteSticky = false;
    cypherEditor && cypherEditor.setAutocompleteSticky(false);
    logs = logs.concat(commandLog("setAutocompleteSticky", autocompleteSticky));
  };

  const goToPosition = (position) => {
    cypherEditor && cypherEditor.goToPosition(position);
    cypherEditor && cypherEditor.focus();
    logs = logs.concat(commandLog("goToPosition", position));
  };

  const goToPositionStart = () => {
    goToPosition(0);
  };

  const goToPositionEnd = () => {
    goToPosition(cypherLength);
  };

  const goToPositionPosition = () => {
    if (isNumberString(positionPosition)) {
      goToPosition(+positionPosition);
    }
  };

  const goToPositionLineColumn = () => {
    if (isNumberString(positionLine) && isNumberString(positionColumn)) {
      goToPosition({ line: +positionLine, column: +positionColumn });
    }
  };

  const isNumberString = v => v === "0" || /^([1-9])([0-9])*$/.test(v);

  const positionPositionChanged = (e) => {
    const { target } = e;
    const { value } = target;
    if (value === "" || isNumberString(value)) {
      positionPosition = value;
    } else {
      e.target.value = positionPosition;
    }
    updateGoButtons();
  };

  const positionLineChanged = (e) => {
    const { target } = e;
    const { value } = target;
    if (value === "" || isNumberString(value)) {
      positionLine = value;
    } else {
      e.target.value = positionLine;
    }
    updateGoButtons();
  };

  const positionColumnChanged = (e) => {
    const { target } = e;
    const { value } = target;
    if (value === "" || isNumberString(value)) {
      positionColumn = value;
    } else {
      e.target.value = positionColumn;
    }
    updateGoButtons();
  };

  const showLongValue = () => {
    if (cypherEditor) {
      cypherEditor.setValue(longQuery);
      updateValue(longQuery);
      logs = logs.concat(commandLog("setValue", longQuery.length + " (long"));
    }
  };

  const showSimpleValue = () => {
    if (cypherEditor) {
      cypherEditor.setValue(simpleQuery);
      updateValue(simpleQuery);
      logs = logs.concat(commandLog("setValue", simpleQuery.length + " (simple"));
    }
  };
</script>

<div class="database">
  <div class="left">
    <div class="setting setting-short">
      <div class="setting-label">Theme</div>
      <div class="setting-values">
        <button class={theme === "light" ? "setting-active" : undefined} on:click={lightTheme}>Light</button>
        <button class={theme === "dark" ? "setting-active" : undefined} on:click={darkTheme}>Dark</button>    
      </div>
    </div>

    <div class="setting setting-short">
      <div class="setting-label">Placeholder</div>
      <div class="setting-values">
        <button class={placeholder === undefined ? "setting-active" : undefined} on:click={setNoPlaceholder}>None</button>
        <button class={placeholder === samplePlaceholder ? "setting-active" : undefined} on:click={setSamplePlaceholder}>Sample</button>    
      </div>
    </div>

    <div class="setting setting-short">
      <div class="setting-label">Schema</div>
      <div class="setting-values">
        <button class={schema === simpleSchema ? "setting-active" : undefined} on:click={showSimpleSchema}>Simple</button>
        <button class={schema === neo4jSchema ? "setting-active" : undefined} on:click={showLongSchema}>Long</button>    
      </div>
    </div>

    <div class="setting setting-short">
      <div class="setting-label">Lint</div>
      <div class="setting-values">
        <button class={lint === true ? "setting-active" : undefined} on:click={enableLint}>True</button>
        <button class={lint === false ? "setting-active" : undefined} on:click={disableLint}>False</button>    
      </div>
    </div>

    <div class="setting">
      <div class="setting-label">Line Numbers</div>
      <div class="setting-values">
        <button class={lineNumbers === true ? "setting-active" : undefined} on:click={showLineNumbers}>True</button>
        <button class={lineNumbers === false ? "setting-active" : undefined} on:click={hideLineNumbers}>False</button>    
      </div>
    </div>

    <div class="setting setting-long">
      <div class="setting-label">Line Number Formatter</div>
      <div class="setting-values">
        <button class={lineNumberFormatter === defaultLineNumberFormatter ? "setting-active" : undefined} on:click={showDefaultLineNumberFormatter}>Default</button>
        <button class={lineNumberFormatter === noneLineNumberFormatter ? "setting-active" : undefined} on:click={showNoneLineNumberFormatter}>None</button>
        <button class={lineNumberFormatter === customLineNumberFormatter ? "setting-active" : undefined} on:click={showCustomLineNumberFormatter}>Custom</button>
      </div>
    </div>

    <div class="setting setting-long">
      <div class="setting-label">Read Only</div>
      <div class="setting-values">
        <button class={readOnly === false ? "setting-active" : undefined} on:click={makeReadable}>False</button>
        <button class={readOnly === true ? "setting-active" : undefined} on:click={makeReadOnly}>True</button>
        <button class={readOnly === "nocursor" ? "setting-active" : undefined} on:click={makeReadOnlyNoCursor}>No Cursor</button>
      </div>
    </div>

    <div class="setting">
      <div class="setting-label">Autocomplete</div>
      <div class="setting-values">
        <button class={autocomplete === true ? "setting-active" : undefined} on:click={enableAutocomplete}>True</button>
        <button class={autocomplete === false ? "setting-active" : undefined} on:click={disableAutocomplete}>False</button>    
      </div>
    </div>

    <div class="setting setting-long">
      <div class="setting-label">Autocomplete Triggers</div>
      <div class="setting-values">
        <button class={autocompleteTriggerStrings === initialOptions.autocompleteTriggerStrings ? "setting-active" : undefined} on:click={showDefaultAutocompleteTriggerStrings}>Default</button>
        <button class={autocompleteTriggerStrings === false ? "setting-active" : undefined} on:click={showNoAutocompleteTriggerStrings}>False</button>    
      </div>
    </div>

    <div class="setting setting-long">
      <div class="setting-label">Autocomplete Sticky</div>
      <div class="setting-values">
        <button class={autocompleteSticky === true ? "setting-active" : undefined} on:click={showStickyAutocomplete}>True</button>
        <button class={autocompleteSticky === false || autocompleteSticky === undefined ? "setting-active" : undefined} on:click={showUnstickyAutocomplete}>False</button>    
      </div>
    </div>

    <div class="setting">
      <div class="setting-label">History</div>
      <div class="setting-values">
        <button on:click={clearHistory}>Clear</button>
      </div>
    </div>

    <div class="setting">
      <div class="setting-label">Focus</div>
      <div class="setting-values">
        <button on:click={focusEditor}>Focus Editor</button>
      </div>
    </div>

    <div class="setting setting-long">
      <div class="setting-label">
        Position
        <button title="start" on:click={goToPositionStart}>start</button>
        <button title="end" on:click={goToPositionEnd}>end</button>
      </div>
      <div class="setting-values">
        <label for="position">position</label>
        <input name="position" type="text" value={positionPosition} on:input={positionPositionChanged}/>
        <button disabled={!goPositionPositionEnabled} on:click={goToPositionPosition}>Go</button>    
      </div>
      <div class="setting-values">
        <label for="line">line</label>
        <input class="short-input" name="line" type="text" value={positionLine} on:input={positionLineChanged}/>
        <label for="column">column</label>
        <input class="short-input" name="column" type="text" value={positionColumn} on:input={positionColumnChanged}/>
        <button disabled={!goPositionLineColumnEnabled} on:click={goToPositionLineColumn}>Go</button>    
      </div>
    </div>

    <div class="setting">
      <div class="setting-label">Value</div>
      <div class="setting-values">
        <button on:click={showLongValue}>Long</button>
        <button on:click={showSimpleValue}>Simple</button>    
      </div>
    </div>
  </div>
  <div class="right">
    <div class="card">
      <h1>{title}</h1>
    </div>
    <div class="card">
      <svelte:component
        {onValueChange}
        {onPositionChange}
        {onFocusChange}
        {onEditorCreate}
        {onAutocompleteOpenChange}
        {onLineClick}
        {initialPosition}
        {initialSchema}
        {initialValue}
        {initialOptions}
        {theme}
        classNames={["editor"]}
        this={editor}/>
    </div>
    <div class="card">
      <div class="info">
        <div class="info-item-long">Position: {positionString}</div>
        <div class="info-item">Length: {cypherLength}</div>
        <div class="info-item">Line Count: {lineCount}</div>
        <div class="info-item">Focused: {focusedString}</div>
        <div class="info-item">Autocompleting: {autocompleteString}</div>
      </div>
    </div>
    <div class="card">
      <h3>Logs</h3>
      <textarea value={logText}/>
    </div>
    <div class="card">
      <div class="results">
        <button on:click={send}> Run Current Query </button>
        <h3>Results</h3>
        {#await promisedResult}
          <p>...waiting</p>
        {:then results}
          {#if results}
            {#each results.records as record}
              <pre>{JSON.stringify(record)}</pre>
            {/each}
          {/if}
        {:catch error}
          <p style="color: red">{error.message}</p>
        {/await}
      </div>
    </div>
  </div>
</div>

// packages/demo-base-react/src/Database.js
import React, { useState, useRef } from "react";
import neo4j from "neo4j-driver";
import {
  neo4jSchema,
  simpleSchema,
  longQuery,
  simpleQuery,
  defaultOptions,
  initialPosition,
  host,
  user,
  pass
} from "demo-base";

const initialSchema = simpleSchema;
const initialValue = longQuery;
const initialOptions = defaultOptions;

const driver = neo4j.driver(host, neo4j.auth.basic(user, pass));

const defaultLineNumberFormatter = undefined;
const noneLineNumberFormatter = (line) => line;
const customLineNumberFormatter = (line, lineCount) => {
  if (line === 1) {
    return "one";
  } else if (line === 2) {
    return "two";
  } else if (line === 3) {
    return "three";
  } else if (line > 3) {
    return line + " / " + lineCount + " prompt$";
  }
};

const samplePlaceholder = "Sample Placeholder";

const Database = ({ CypherEditor, codemirrorVersion, framework, bundler }) => {
  const title = `Cypher Codemirror ${codemirrorVersion} ${framework} ${bundler}`;
  const [cypher, setCypher] = useState(initialValue);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [results, setResults] = useState(null);
  const [theme, setTheme] = useState("light");
  const [position, setPosition] = useState(initialPosition);
  const [autocompleteOpen, setAutocompleteOpen] = useState(false);
  const [focused, setFocused] = useState(true);
  const [editor, setEditor] = useState(null);
  const [lineNumbers, setLineNumbers] = useState(
    initialOptions.lineNumbers || true
  );
  const [lineNumberFormatterObject, setLineNumberFormatterObject] = useState({
    lineNumberFormatter: initialOptions.lineNumberFormatter
  });
  const { lineNumberFormatter } = lineNumberFormatterObject;
  const [schema, setSchema] = useState(initialSchema);
  const [readOnly, setReadOnly] = useState(initialOptions.readOnly || false);
  const [autocomplete, setAutocomplete] = useState(
    initialOptions.autocomplete || true
  );
  const [autocompleteTriggerStrings, setAutocompleteTriggerStrings] = useState(
    initialOptions.autocompleteTriggerStrings || undefined
  );
  const [autocompleteSticky, setAutocompleteSticky] = useState(
    initialOptions.autocompleteSticky
  );
  const [placeholder, setPlaceholder] = useState(initialOptions.placeholder);
  const [lint, setLint] = useState(initialOptions.lint || true);
  const [positionPosition, setPositionPosition] = useState("0");
  const [positionLine, setPositionLine] = useState("1");
  const [positionColumn, setPositionColumn] = useState("0");
  const [goPositionPositionEnabled, setGoPositionPositionEnabled] =
    useState(false);
  const [goPositionLineColumnEnabled, setGoPositionLineColumnEnabled] =
    useState(false);
  const [lineCount, setLineCount] = useState(0);
  const [logs, setLogs] = useState([]);
  const [logText, setLogText] = useState("");
  const textareaRef = useRef(null);

  const commandLog = (command, argument) => {
    return {
      type: "command",
      label: command,
      command,
      argument
    };
  };

  const eventLog = (event, argument) => {
    return {
      type: "event",
      label: event,
      event,
      argument
    };
  };

  const getLogText = logs => logs.map(({ type, label, argument }) => type + " " + label + " " + printArgument(argument)).join("\n");

  const changeLogs = logs => {
    setLogs(logs);
    const logText = getLogText(logs);
    setLogText(logText);
    if (textareaRef.current) {
      textareaRef.current.value = logText;
      textareaRef.current.scrollTop = textareaRef.current.scrollHeight;

    }
  };

  const send = () => {
    const session = driver.session();
    setLoading(true);
    session.run(cypher).then(
      (results) => {
        setResults(results);
        setLoading(false);
        setError(null);
      },
      (error) => {
        setResults(null);
        setLoading(false);
        setError(error);
      }
    );
  };

  const updateGoButtons = ({
    cypherEditor = editor,
    positionPosition: goPositionPosition = positionPosition,
    positionLine: goPositionLine = positionLine,
    positionColumn: goPositionColumn = positionColumn
  } = {}) => {
    setGoPositionPositionEnabled(
      isNumberString(goPositionPosition) &&
        cypherEditor.getPositionForValue(+goPositionPosition) !== null
    );
    setGoPositionLineColumnEnabled(
      isNumberString(goPositionLine) &&
        isNumberString(goPositionColumn) &&
        cypherEditor.getPositionForValue({
          line: +goPositionLine,
          column: +goPositionColumn
        }) !== null
    );
  };

  const updateValue = (value) => {
    setCypher(value);
    updateGoButtons();
    editor && setLineCount(editor.getLineCount());
  };

  const onValueChange = (value, change) => {
    changeLogs(logs.concat(eventLog("onValueChange", value ? value.length : 0)));
    updateValue(value);
  };

  const onPositionChange = (positionObject) => {
    changeLogs(logs.concat(eventLog("onPositionChange", positionObject)));
    setPosition(positionObject);
  };

  const onAutocompleteOpenChange = (autocompleteOpen) => {
    changeLogs(logs.concat(eventLog("onAutocompleteOpenChange", autocompleteOpen)));
    setAutocompleteOpen(autocompleteOpen);
  };

  const onLineClick = (line, event) => {
    changeLogs(logs.concat(eventLog("onLineClick", line)));
  };

  const onEditorCreate = (editor) => {
    changeLogs(logs.concat(eventLog("onEditorCreate", "")));
    setEditor(editor);
    setPosition(editor.getPosition());
    setLineCount(editor.getLineCount());
    updateGoButtons({ cypherEditor: editor });
  };

  const onFocusChange = (focused) => {
    changeLogs(logs.concat(eventLog("onFocusChange", focused)));
    setFocused(focused);
  };

  const lightTheme = () => {
    changeLogs(logs.concat(commandLog("setTheme", "light")));
    setTheme("light");
  };

  const darkTheme = () => {
    changeLogs(logs.concat(commandLog("setTheme", "dark")));
    setTheme("dark");
  };

  const cypherLength = cypher.length;
  const positionString = position ? JSON.stringify(position) : "";
  const focusedString = focused + "";
  const autocompleteString = autocompleteOpen + "";

  const printArgument = argument => {
    try {
      return JSON.stringify(argument);
    } catch (e) {
      return "error " + e.message + " " + argument;
    }
  };

  const showLineNumbers = () => {
    changeLogs(logs.concat(commandLog("setLineNumbers", true)));
    setLineNumbers(true);
    editor && editor.setLineNumbers(true);
  };

  const hideLineNumbers = () => {
    changeLogs(logs.concat(commandLog("setLineNumbers", false)));
    setLineNumbers(false);
    editor && editor.setLineNumbers(false);
  };

  const setNoPlaceholder = () => {
    changeLogs(logs.concat(commandLog("setPlaceholder", undefined)));
    setPlaceholder(undefined);
    editor && editor.setPlaceholder(undefined);
  };

  const setSamplePlaceholder = () => {
    changeLogs(logs.concat(commandLog("setPlaceholder", samplePlaceholder)));
    setPlaceholder(samplePlaceholder);
    editor && editor.setPlaceholder(samplePlaceholder);
  };

  const makeReadable = () => {
    changeLogs(logs.concat(commandLog("setReadOnly", false)));
    setReadOnly(false);
    editor && editor.setReadOnly(false);
  };

  const makeReadOnly = () => {
    changeLogs(logs.concat(commandLog("setReadOnly", true)));
    setReadOnly(true);
    editor && editor.setReadOnly(true);
  };

  const makeReadOnlyNoCursor = () => {
    changeLogs(logs.concat(commandLog("setReadOnly", "nocursor")));
    setReadOnly("nocursor");
    editor && editor.setReadOnly("nocursor");
  };

  const enableAutocomplete = () => {
    changeLogs(logs.concat(commandLog("setAutocomplete", true)));
    setAutocomplete(true);
    editor && editor.setAutocomplete(true);
  };

  const disableAutocomplete = () => {
    changeLogs(logs.concat(commandLog("setAutocomplete", false)));
    setAutocomplete(false);
    editor && editor.setAutocomplete(false);
  };

  const enableLint = () => {
    changeLogs(logs.concat(commandLog("setLint", true)));
    setLint(true);
    editor && editor.setLint(true);
  };

  const disableLint = () => {
    changeLogs(logs.concat(commandLog("setLint", false)));
    setLint(false);
    editor && editor.setLint(false);
  };

  const clearHistory = () => {
    changeLogs(logs.concat(commandLog("clearHistory", "")));
    editor && editor.clearHistory();
  };

  const focusEditor = () => {
    changeLogs(logs.concat(commandLog("focus", "")));
    editor && editor.focus();
  };

  const showDefaultLineNumberFormatter = () => {
    changeLogs(logs.concat(commandLog("setLineNumberFormatter", "default")));
    setLineNumberFormatterObject({
      lineNumberFormatter: defaultLineNumberFormatter
    });
    editor && editor.setLineNumberFormatter(defaultLineNumberFormatter);
  };

  const showNoneLineNumberFormatter = () => {
    changeLogs(logs.concat(commandLog("setLineNumberFormatter", "none")));
    setLineNumberFormatterObject({
      lineNumberFormatter: noneLineNumberFormatter
    });
    editor && editor.setLineNumberFormatter(noneLineNumberFormatter);
  };

  const showCustomLineNumberFormatter = () => {
    changeLogs(logs.concat(commandLog("setLineNumberFormatter", "custom")));
    setLineNumberFormatterObject({
      lineNumberFormatter: customLineNumberFormatter
    });
    editor && editor.setLineNumberFormatter(customLineNumberFormatter);
  };

  const showSimpleSchema = () => {
    changeLogs(logs.concat(commandLog("setSchema", "simple")));
    setSchema(simpleSchema);
    editor && editor.setSchema(simpleSchema);
  };

  const showLongSchema = () => {
    changeLogs(logs.concat(commandLog("setSchema", "long")));
    setSchema(neo4jSchema);
    editor && editor.setSchema(neo4jSchema);
  };

  const showDefaultAutocompleteTriggerStrings = () => {
    changeLogs(logs.concat(commandLog("setAutocompleteTriggerStrings", initialOptions.autocompleteTriggerStrings)));
    setAutocompleteTriggerStrings(initialOptions.autocompleteTriggerStrings);
    editor &&
      editor.setAutocompleteTriggerStrings(
        initialOptions.autocompleteTriggerStrings
      );
  };

  const showNoAutocompleteTriggerStrings = () => {
    changeLogs(logs.concat(commandLog("setAutocompleteTriggerStrings", false)));
    setAutocompleteTriggerStrings(false);
    editor && editor.setAutocompleteTriggerStrings(false);
  };

  const showStickyAutocomplete = () => {
    changeLogs(logs.concat(commandLog("setAutocompleteSticky", true)));
    setAutocompleteSticky(true);
    editor && editor.setAutocompleteSticky(true);
  };

  const showUnstickyAutocomplete = () => {
    changeLogs(logs.concat(commandLog("setAutocompleteSticky", false)));
    setAutocompleteSticky(false);
    editor && editor.setAutocompleteSticky(false);
  };

  const goToPosition = (position) => {
    changeLogs(logs.concat(commandLog("goToPosition", position)));
    editor && editor.goToPosition(position);
    editor && editor.focus();
  };

  const goToPositionStart = () => {
    goToPosition(0);
  };

  const goToPositionEnd = () => {
    goToPosition(cypherLength);
  };

  const goToPositionPosition = () => {
    if (isNumberString(positionPosition)) {
      goToPosition(+positionPosition);
    }
  };

  const goToPositionLineColumn = () => {
    if (isNumberString(positionLine) && isNumberString(positionColumn)) {
      goToPosition({ line: +positionLine, column: +positionColumn });
    }
  };

  const isNumberString = (v) => v === "0" || /^([1-9])([0-9])*$/.test(v);

  const positionPositionChanged = (e) => {
    const { target } = e;
    const { value } = target;
    let updateParams;
    if (value === "" || isNumberString(value)) {
      setPositionPosition(value);
      updateParams = { positionPosition: value };
    } else {
      e.target.value = positionPosition;
    }
    updateGoButtons(updateParams);
  };

  const positionLineChanged = (e) => {
    const { target } = e;
    const { value } = target;
    let updateParams;
    if (value === "" || isNumberString(value)) {
      setPositionLine(value);
      updateParams = { positionLine: value };
    } else {
      e.target.value = positionLine;
    }
    updateGoButtons(updateParams);
  };

  const positionColumnChanged = (e) => {
    const { target } = e;
    const { value } = target;
    let updateParams;
    if (value === "" || isNumberString(value)) {
      setPositionColumn(value);
      updateParams = { positionColumn: value };
    } else {
      e.target.value = positionColumn;
    }
    updateGoButtons(updateParams);
  };

  const showLongValue = () => {
    if (editor) {
      changeLogs(logs.concat(commandLog("setValue", longQuery.length + " (long)")));
      editor && editor.setValue(longQuery);
      updateValue(longQuery);
    }
  };

  const showSimpleValue = () => {
    if (editor) {
      changeLogs(logs.concat(commandLog("setValue", simpleQuery.length + " (simple)")));
      editor && editor.setValue(simpleQuery);
      updateValue(simpleQuery);
    }
  };

  let content = "";
  if (loading) {
    content = <p>...waiting</p>;
  } else if (error) {
    content = <p style={{ color: "red" }}>{error.message}</p>;
  } else if (results) {
    content = results.records.map((record, i) => (
      <pre key={i}>{JSON.stringify(record)}</pre>
    ));
  }

  return (
    <div className="database">
      <div className="left">
        <div className="setting setting-short">
          <div className="setting-label">Theme</div>
          <div className="setting-values">
            <button
              className={theme === "light" ? "setting-active" : undefined}
              onClick={lightTheme}
            >
              Light
            </button>
            <button
              className={theme === "dark" ? "setting-active" : undefined}
              onClick={darkTheme}
            >
              Dark
            </button>
          </div>
        </div>

        <div className="setting setting-short">
          <div className="setting-label">Placeholder</div>
          <div className="setting-values">
            <button
              className={placeholder === undefined ? "setting-active" : undefined}
              onClick={setNoPlaceholder}
            >
              None
            </button>
            <button
              className={placeholder === samplePlaceholder ? "setting-active" : undefined}
              onClick={setSamplePlaceholder}
            >
              Sample
            </button>
          </div>
        </div>

        <div className="setting setting-short">
          <div className="setting-label">Schema</div>
          <div className="setting-values">
            <button
              className={schema === simpleSchema ? "setting-active" : undefined}
              onClick={showSimpleSchema}
            >
              Simple
            </button>
            <button
              className={schema === neo4jSchema ? "setting-active" : undefined}
              onClick={showLongSchema}
            >
              Long
            </button>
          </div>
        </div>

        <div className="setting setting-short">
          <div className="setting-label">Lint</div>
          <div className="setting-values">
            <button
              className={lint === true ? "setting-active" : undefined}
              onClick={enableLint}
            >
              True
            </button>
            <button
              className={lint === false ? "setting-active" : undefined}
              onClick={disableLint}
            >
              False
            </button>
          </div>
        </div>

        <div className="setting">
          <div className="setting-label">Line Numbers</div>
          <div className="setting-values">
            <button
              className={lineNumbers === true ? "setting-active" : undefined}
              onClick={showLineNumbers}
            >
              True
            </button>
            <button
              className={lineNumbers === false ? "setting-active" : undefined}
              onClick={hideLineNumbers}
            >
              False
            </button>
          </div>
        </div>

        <div className="setting setting-long">
          <div className="setting-label">Line Number Formatter</div>
          <div className="setting-values">
            <button
              className={
                lineNumberFormatter === defaultLineNumberFormatter
                  ? "setting-active"
                  : undefined
              }
              onClick={showDefaultLineNumberFormatter}
            >
              Default
            </button>
            <button
              className={
                lineNumberFormatter === noneLineNumberFormatter
                  ? "setting-active"
                  : undefined
              }
              onClick={showNoneLineNumberFormatter}
            >
              None
            </button>
            <button
              className={
                lineNumberFormatter === customLineNumberFormatter
                  ? "setting-active"
                  : undefined
              }
              onClick={showCustomLineNumberFormatter}
            >
              Custom
            </button>
          </div>
        </div>

        <div className="setting setting-long">
          <div className="setting-label">Read Only</div>
          <div className="setting-values">
            <button
              className={readOnly === false ? "setting-active" : undefined}
              onClick={makeReadable}
            >
              False
            </button>
            <button
              className={readOnly === true ? "setting-active" : undefined}
              onClick={makeReadOnly}
            >
              True
            </button>
            <button
              className={readOnly === "nocursor" ? "setting-active" : undefined}
              onClick={makeReadOnlyNoCursor}
            >
              No Cursor
            </button>
          </div>
        </div>

        <div className="setting">
          <div className="setting-label">Autocomplete</div>
          <div className="setting-values">
            <button
              className={autocomplete === true ? "setting-active" : undefined}
              onClick={enableAutocomplete}
            >
              True
            </button>
            <button
              className={autocomplete === false ? "setting-active" : undefined}
              onClick={disableAutocomplete}
            >
              False
            </button>
          </div>
        </div>

        <div className="setting setting-long">
          <div className="setting-label">Autocomplete Triggers</div>
          <div className="setting-values">
            <button
              className={
                autocompleteTriggerStrings ===
                initialOptions.autocompleteTriggerStrings
                  ? "setting-active"
                  : undefined
              }
              onClick={showDefaultAutocompleteTriggerStrings}
            >
              Default
            </button>
            <button
              className={
                autocompleteTriggerStrings === false
                  ? "setting-active"
                  : undefined
              }
              onClick={showNoAutocompleteTriggerStrings}
            >
              False
            </button>
          </div>
        </div>

        <div className="setting setting-long">
          <div className="setting-label">Autocomplete Sticky</div>
          <div className="setting-values">
            <button
              className={
                autocompleteSticky === true ? "setting-active" : undefined
              }
              onClick={showStickyAutocomplete}
            >
              True
            </button>
            <button
              className={
                autocompleteSticky === false || autocompleteSticky === undefined
                  ? "setting-active"
                  : undefined
              }
              onClick={showUnstickyAutocomplete}
            >
              False
            </button>
          </div>
        </div>

        <div className="setting">
          <div className="setting-label">History</div>
          <div className="setting-values">
            <button onClick={clearHistory}>Clear</button>
          </div>
        </div>

        <div className="setting">
          <div className="setting-label">Focus</div>
          <div className="setting-values">
            <button onClick={focusEditor}>Focus Editor</button>
          </div>
        </div>

        <div className="setting setting-long">
          <div className="setting-label">
            Position
            <button title="start" onClick={goToPositionStart}>
              start
            </button>
            <button title="end" onClick={goToPositionEnd}>
              end
            </button>
          </div>
          <div className="setting-values">
            <label htmlFor="position">position</label>
            <input
              name="position"
              type="text"
              value={positionPosition}
              onInput={positionPositionChanged}
            />
            <button
              disabled={!goPositionPositionEnabled}
              onClick={goToPositionPosition}
            >
              Go
            </button>
          </div>
          <div className="setting-values">
            <label htmlFor="line">line</label>
            <input
              className="short-input"
              name="line"
              type="text"
              value={positionLine}
              onInput={positionLineChanged}
            />
            <label htmlFor="column">column</label>
            <input
              className="short-input"
              name="column"
              type="text"
              value={positionColumn}
              onInput={positionColumnChanged}
            />
            <button
              disabled={!goPositionLineColumnEnabled}
              onClick={goToPositionLineColumn}
            >
              Go
            </button>
          </div>
        </div>

        <div className="setting">
          <div className="setting-label">Value</div>
          <div className="setting-values">
            <button onClick={showLongValue}>Long</button>
            <button onClick={showSimpleValue}>Simple</button>    
          </div>
        </div>
      </div>
      <div className="right">
        <div className="card">
          <h1>{title}</h1>
        </div>
        <div className="card">
          <CypherEditor
            onValueChange={onValueChange}
            onPositionChange={onPositionChange}
            onFocusChange={onFocusChange}
            onAutocompleteOpenChange={onAutocompleteOpenChange}
            onLineClick={onLineClick}
            onEditorCreate={onEditorCreate}
            initialPosition={initialPosition}
            initialSchema={initialSchema}
            initialValue={initialValue}
            initialOptions={initialOptions}
            theme={theme}
            classNames={["editor"]}
          />
        </div>
        <div className="card">
          <div className="info">
            <div className="info-item-long">Position: {positionString}</div>
            <div className="info-item">Length: {cypherLength}</div>
            <div className="info-item">Line Count: {lineCount}</div>
            <div className="info-item">Focused: {focusedString}</div>
            <div className="info-item">
              Autocompleting: {autocompleteString}
            </div>
          </div>
        </div>
        <div className="card">
          <div className="logs">
            <h3>Logs</h3>
            <textarea value={logText} ref={textareaRef}/>
          </div>
        </div>
        <div className="card">
          <div className="results">
            <button onClick={send}> Run Current Query </button>
            <h3>Results</h3>
            {content}
          </div>
        </div>
      </div>
    </div>
  );
};

export default Database;
