// packages/svelte-codemirror-cypher/src/CypherEditor.svelte
<script lang="js">
  import { onMount, onDestroy } from "svelte";

  import "cypher-codemirror/css/cypher-codemirror.css";
  import { createCypherEditor } from "cypher-codemirror";

  const THEME_LIGHT = "light";
  const THEME_DARK = "dark";

  export let initialPosition = undefined;

  export let initialOptions = undefined;

  export let initialSchema = undefined;

  export let onValueChange = undefined;

  export let onFocusChange = undefined;

  export let onScroll = undefined;

  export let onPositionChange = undefined;

  export let classNames = undefined;

  export let initialValue = "MATCH (n) RETURN n LIMIT 10";

  export let theme = THEME_LIGHT;

  export let onEditorCreate = undefined;

  export let onAutocompleteOpenChange = undefined;

  export let onLineClick = undefined;

  $: cypherEditorOptions = { ...(initialOptions || {}) };

  let cypherEditorRef;
  let cypherEditor;
  let cypherEditorSupport;

  $: editorClassNames = (classNames ? classNames : [])
    .concat(theme !== THEME_DARK ? [] : ["cm-dark"])
    .join(" ");

  const valueChanged = (value, changes) => {
    onValueChange && onValueChange(value, changes);
  };

  const focusChanged = (focused) => {
    onFocusChange && onFocusChange(focused);
  };

  const focused = () => {
    focusChanged(true);
  };

  const blurred = () => {
    focusChanged(false);
  };

  const scrollChanged = (scrollInfo) => {
    onScroll && onScroll(scrollInfo);
  };

  const positionChanged = (positionObject) => {
    onPositionChange && onPositionChange(positionObject);
  };

  const autocompleteChanged = (autocompleteOpen) => {
    onAutocompleteOpenChange && onAutocompleteOpenChange(autocompleteOpen);
  };

  const lineClicked = (line, event) => {
    onLineClick && onLineClick(line, event);
  };

  onMount(() => {
    const { autofocus = true, ...options } = cypherEditorOptions;
    const { editor, editorSupport } = createCypherEditor(
      cypherEditorRef,
      options
    );
    cypherEditor = editor;
    cypherEditorSupport = editorSupport;

    if (autofocus) {
      cypherEditor.focus();
    }
    if (initialSchema) {
      editorSupport.setSchema(initialSchema);
    }
    cypherEditor.setValue(initialValue);
    if (initialPosition) {
      cypherEditor.goToPosition(initialPosition);
    }
    cypherEditor.on("change", valueChanged);
    cypherEditor.on("focus", focused);
    cypherEditor.on("blur", blurred);
    cypherEditor.on("scroll", scrollChanged);
    cypherEditor.on("position", positionChanged);
    cypherEditor.on("autocomplete", autocompleteChanged);
    cypherEditor.on("lineclick", lineClicked);

    onEditorCreate && onEditorCreate(cypherEditor);
  });

  onDestroy(() => {
    if (cypherEditor) {
      cypherEditor.off("change", valueChanged);
      cypherEditor.off("focus", focused);
      cypherEditor.off("blur", blurred);
      cypherEditor.off("scroll", scrollChanged);
      cypherEditor.off("position", positionChanged);
      cypherEditor.off("autocomplete", autocompleteChanged);
      cypherEditor.off("lineclick", lineClicked);

      cypherEditor.destroy();
    }
  });
</script>

<div class={editorClassNames} bind:this={cypherEditorRef} />

// packages/react-codemirror-cypher/src/CypherEditor.js
import React, { Component } from "react";
import { createCypherEditor } from "cypher-codemirror";
import "cypher-codemirror/css/cypher-codemirror.css";

const THEME_LIGHT = "light";
const THEME_DARK = "dark";

class CypherEditor extends Component {
  constructor(props) {
    super(props);
    this.state = {
      focused: false
    };
  }

  setEditorRef = (ref) => {
    this.editorRef = ref;
  };

  valueChanged = (value, changes) => {
    const { onValueChange } = this.props;
    onValueChange && onValueChange(value);
  };

  focusChanged = (focused) => {
    const { onFocusChange } = this.props;
    this.setState({ focused });
    onFocusChange && onFocusChange(focused);
  };

  focused = () => {
    this.focusChanged(true);
  };

  blurred = () => {
    this.focusChanged(false);
  };

  scrollChanged = (scrollInfo) => {
    const { onScroll } = this.props;
    onScroll && onScroll(scrollInfo);
  };

  positionChanged = (positionObject) => {
    const { onPositionChange } = this.props;
    onPositionChange && onPositionChange(positionObject);
  };

  autocompleteChanged = (autocompleteOpen) => {
    const { onAutocompleteOpenChange } = this.props;
    onAutocompleteOpenChange && onAutocompleteOpenChange(autocompleteOpen);
  };

  lineClicked = (line, event) => {
    const { onLineClick } = this.props;
    onLineClick && onLineClick(line, event);
  };

  componentDidMount() {
    const {
      initialOptions,
      initialSchema,
      initialValue = "MATCH (n) RETURN n LIMIT 10",
      initialPosition,
      onEditorCreate
    } = this.props;
    const { autofocus = true, ...options } = initialOptions || {};
    const { editor, editorSupport } = createCypherEditor(
      this.editorRef,
      options
    );
    this.cypherEditor = editor;

    if (autofocus) {
      this.cypherEditor.focus();
    }
    if (initialSchema) {
      editorSupport.setSchema(initialSchema);
    }
    this.cypherEditor.setValue(initialValue);
    if (initialPosition) {
      this.cypherEditor.goToPosition(initialPosition);
    }
    this.cypherEditor.on("change", this.valueChanged);
    this.cypherEditor.on("focus", this.focused);
    this.cypherEditor.on("blur", this.blurred);
    this.cypherEditor.on("scroll", this.scrollChanged);
    this.cypherEditor.on("position", this.positionChanged);
    this.cypherEditor.on("autocomplete", this.autocompleteChanged);
    this.cypherEditor.on("lineclick", this.lineClicked);

    onEditorCreate && onEditorCreate(this.cypherEditor);
  }

  componentWillUnmount() {
    if (this.cypherEditor) {
      this.cypherEditor.off("change", this.valueChanged);
      this.cypherEditor.off("focus", this.focused);
      this.cypherEditor.off("blur", this.blurred);
      this.cypherEditor.off("scroll", this.scrollChanged);
      this.cypherEditor.off("position", this.positionChanged);
      this.cypherEditor.off("autocomplete", this.autocompleteChanged);
      this.cypherEditor.off("lineclick", this.lineClicked);

      this.cypherEditor.destroy();
    }
  }

  render() {
    const { classNames, theme = THEME_LIGHT } = this.props;
    const editorClassNames = (classNames ? classNames : [])
      .concat(theme !== THEME_DARK ? [] : ["cm-dark"])
      .join(" ");

    return <div className={editorClassNames} ref={this.setEditorRef}></div>;
  }
}

export default CypherEditor;
