// packages/demo-codemirror-6-vite-svelte/src/components/Database.svelte
<script lang="ts">

	import neo4j from 'neo4j-driver';
  import CypherEditor from 'svelte-codemirror-cypher';
	import { neo4jSchema, defaultQuery, initialPosition } from 'demo-base';

	const driver = neo4j.driver("neo4j://localhost:7687",
		neo4j.auth.basic("neo4j", "asdfgh")
	);

	let cypher = defaultQuery;

	let theme = 'light';

	const lightTheme = () => {
		theme = 'light';
	};

	const darkTheme = () => {
		theme = 'dark';
	};

	let promisedResult;

	const send = () => {
		const session = driver.session();
		promisedResult = session.run(cypher); 
	};

  const onValueChange = (value: string, change: any) => {
		cypher = value;
  };

</script>

<main>

  <CypherEditor {onValueChange} {initialPosition} autoCompleteSchema={neo4jSchema} bind:cypher={cypher} bind:theme={theme} />
	<button on:click={lightTheme}>Light theme</button>
	<button on:click={darkTheme}>Dark theme</button>
	<button on:click={send}>
		Run
	</button>

	<div>
		<h3>Results</h3>
		{#await promisedResult}
			<p>...waiting</p>
		{:then results}
			{#if results}
				{#each results.records as record}
					<pre>{JSON.stringify(record)}</pre>
				{/each}
			{/if}
		{:catch error}
			<p style="color: red">{error.message}</p>
		{/await}
	</div>
</main>

<style>
	main {
		text-align: center;
		padding: 1em;
		max-width: 240px;
		margin: 0 auto;
	}

	@media (min-width: 640px) {
		main {
			max-width: none;
		}
	}
</style>

// packages/demo-codemirror-6-webpack-react/src/components/Database.js
import React, { useState } from 'react';
import neo4j from 'neo4j-driver';
import CypherEditor from 'react-codemirror-cypher';
import { neo4jSchema, defaultQuery, initialPosition } from 'demo-base';

const driver = neo4j.driver("neo4j://localhost:7687",
  neo4j.auth.basic("neo4j", "asdfgh")
);

const Database = () => {
  const [cypher, setCypher] = useState(defaultQuery);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [results, setResults] = useState(null);
  const [theme, setTheme] = useState('light');

  const send = () => {
		const session = driver.session();
    setLoading(true);
		session.run(cypher)
      .then(results => {
        setResults(results);
        setLoading(false);
        setError(null);
      }, error => {
        setResults(null);
        setLoading(false);
        setError(error);
      });
	};

  const onValueChange = (value, change) => {
		setCypher(value);
  };

  const lightTheme = () => {
    setTheme('light');
  };

  const darkTheme = () => {
    setTheme('dark');
  };

  let content = '';
  if (loading) {
    content = (<p>...waiting</p>);
  } else if (error) {
    content = (<p style="color: red">{error.message}</p>);
  } else if (results) {
    content = results.records.map((record, i) => (<pre key={i}>{JSON.stringify(record)}</pre>))
  }

  return (
    <main>
      <CypherEditor onValueChange={onValueChange} initialPosition={initialPosition} autoCompleteSchema={neo4jSchema} cypher={cypher} theme={theme} />
      <button onClick={lightTheme}>Light theme</button>
      <button onClick={darkTheme}>Dark theme</button>
      <button onClick={send}>
        Run
      </button>

      <div>
        <h3>Results</h3>
        {content}
      </div>
    </main>
  );
};

export default Database;
